from typing import Union

from litchi_wp.enums import ActionType as ActionType

class Action:
    type: ActionType
    param: Union[int | float]
    def __init__(self, actiontype: ActionType = ..., param: Union[int, float] = ...) -> None: ...
    def set_type(self, actiontype: ActionType): ...
    def set_param(self, param: Union[int, float]): ...
    def delete(self) -> None: ...
    def set_stay_for(self, msec: int): ...
    def set_take_photo(self) -> None: ...
    def set_start_rec(self) -> None: ...
    def set_stop_rec(self) -> None: ...
    def set_rotate(self, deg: Union[int, float]): ...
    def set_tilt_cam(self, deg: Union[int, float]): ...
