from litchi_wp.enums import AltitudeMode as AltitudeMode

class Altitude:
    value: float
    mode: Altitude
    def __init__(self, value: float = ..., mode: AltitudeMode = ...) -> None: ...
    def set_mode(self, mode: AltitudeMode): ...
    def set_value(self, value: float): ...
