from litchi_wp.enums import GimbalMode as GimbalMode

class Gimbal:
    mode: GimbalMode
    pitchangle: float
    def __init__(self, mode: GimbalMode = GimbalMode.DISABLED, pitchangle: float = 0) -> None: ...
    def set_focus_poi(self) -> None: ...
    def set_interpolate(self, pitchangle: float): ...
    def set_mode(self, mode: GimbalMode): ...
    def set_pitchangle(self, pitchangle: float): ...
