

class Photo:
    time_interval: float
    distance_interval: float
    def __init__(self, time_interval: float = ..., distance_interval: float = ...) -> None: ...
    def set_time_interval(self, interval: float): ...
    def set_distance_interval(self, interval: float): ...
