from litchi_wp.enums import AltitudeMode as AltitudeMode

class Poi:
    lat: float
    lon: float
    altitude: float
    altitude_mode: AltitudeMode
    def __init__(self, lat: float = 0, lon: float = 0, altitude: float = 0, altitude_mode: AltitudeMode = AltitudeMode.MSL) -> None: ...
    def set_coordinates(self, lat: float, lon: float): ...
    def set_altitude(self, altitude: float): ...
    def set_altitude_mode(self, altitude_mode: AltitudeMode): ...
