from litchi_wp.enums import AltitudeMode as AltitudeMode

class Poi:
    lat: float
    lon: float
    altitude: float
    altitude_mode: AltitudeMode
    def __init__(self, lat: float = ..., lon: float = ..., altitude: float = ..., altitude_mode: AltitudeMode = ...) -> None: ...
    def set_coordinates(self, lat: float, lon: float): ...
    def set_altitude(self, altitude: float): ...
    def set_altitude_mode(self, altitude_mode: AltitudeMode): ...
